export default {
  hint: 'Twinkle twinkle...',
  notes: [
    { note: 'C', octave: 4, duration: 'q', given: true },
    { note: 'C', octave: 4, duration: 'q' },
    { note: 'G', octave: 4, duration: 'q' },
    { note: 'G', octave: 4, duration: 'q' },
    { note: 'A', octave: 4, duration: 'q', given: true },
    { note: 'A', octave: 4, duration: 'q' },
    { note: 'G', octave: 4, duration: 'h' },
  ],
  palette: [
    { note: 'C', transform: 'incSides' },
    { note: 'C#', transform: 'rotateC' },
    { note: 'D', transform: 'incSides' },
    { note: 'D#', transform: 'incSkewX' },
    { note: 'E', transform: 'scaleDown' },
    { note: 'F', transform: 'rotateCC' },
    { note: 'F#', transform: 'shiftWarm' },
    { note: 'G', transform: 'incStar' },
    { note: 'G#', transform: 'decSkewX' },
    { note: 'A', transform: 'shiftWarm' },
    { note: 'A#', transform: 'decSkewY' },
    { note: 'B', transform: 'shiftCool' },
  ],
  startShape: {
    sideCount: 7,
    radius: 70,
    xCenter: 400,
    yCenter: 200,
    colorVal: 1,
    rotation: 0,
    skewX: 0,
    skewY: 0,
    scale: 1,
    starPow: 1,
  },
}
