export default {
  hint: 'with an oink oink here...',
  barLength: 4,
  notes: [
    { note: 'C', octave: 5, duration: 'q', given: true },
    { note: 'C', octave: 5, duration: 'q', given: true },
    { note: 'C', octave: 5, duration: 'q', given: true },
    { note: 'G', octave: 4, duration: 'q' },
    { note: 'A', octave: 4, duration: 'q' },
    { note: 'A', octave: 4, duration: 'q' },
    { note: 'G', octave: 4, duration: 'h', given: true },
    { note: 'E', octave: 4, duration: 'q' },
    { note: 'E', octave: 4, duration: 'q' },
    { note: 'D', octave: 4, duration: 'q', given: true },
    { note: 'D', octave: 4, duration: 'q', given: true },
    { note: 'C', octave: 4, duration: 'w', given: true },
  ],
  palette: [
    { note: 'D', transform: 'incSides' },
    { note: 'E', transform: 'scaleUp' },
    { note: 'F', transform: 'shiftWarm' },
    { note: 'G', transform: 'incSkewY' },
    { note: 'A', transform: 'shiftWarm' },
    { note: 'B', transform: 'incSkewX', octave: 4 },
    { note: 'C', transform: 'incStar', octave: 5 },
  ],
  startShape: {
    sideCount: 4,
    radius: 20,
    xCenter: 100,
    yCenter: 100,
    colorVal: 1,
    rotation: 0,
    skewX: 0,
    skewY: 0,
    scale: 1,
    starPow: 1,
  },
}
