export default {
  hint: 'Going up!',
  barLength: 8,
  strategy: 'linear',
  notes: [
    { note: 'C', octave: 4, duration: 'q', given: true },
    { note: 'C#', octave: 4, duration: 'q', given: true },
    { note: 'D', octave: 4, duration: 'q', given: true },
    { note: 'D#', octave: 4, duration: 'q', given: true },
    { note: 'E', octave: 4, duration: 'q', given: true },
    { note: 'F', octave: 4, duration: 'q' },
    { note: 'F#', octave: 4, duration: 'q' },
    { note: 'G', octave: 4, duration: 'q' },
    { note: 'G#', octave: 4, duration: 'q' },
    { note: 'A', octave: 4, duration: 'q', given: true },
    { note: 'A#', octave: 4, duration: 'q', given: true },
    { note: 'B', octave: 4, duration: 'q', given: true },
    { note: 'C', octave: 5, duration: 'q', given: true },
  ],
  palette: [
    { note: 'C', transform: 'shiftCool', octave: 4 },
    { note: 'C#', transform: 'shiftCool', octave: 4 },
    { note: 'D', transform: 'shiftCool', octave: 4 },
    { note: 'D#', transform: 'shiftCool', octave: 4 },
    { note: 'E', transform: 'shiftCool', octave: 4 },
    { note: 'F', transform: 'shiftCool', octave: 4 },
    { note: 'F#', transform: 'shiftCool', octave: 4 },
    { note: 'G', transform: 'shiftCool', octave: 4 },
    { note: 'G#', transform: 'shiftCool', octave: 4 },
    { note: 'A', transform: 'shiftCool', octave: 4 },
    { note: 'A#', transform: 'shiftCool', octave: 4 },
    { note: 'B', transform: 'shiftCool', octave: 4 },
    { note: 'C', transform: 'shiftCool', octave: 5 },
  ],
  startShape: {
    sideCount: 3,
    radius: 50,
    xCenter: 100,
    yCenter: 100,
    colorVal: 0.3,
    rotation: 0,
    skewX: 0,
    skewY: 0,
    scale: 1,
    starPow: 1,
  },
}
